services:
  backend:
    depends_on:
      - postgres
    container_name: backend
    build: django/backend/
    image: backend
    ports:
      - "8000:8000"
    networks:
      - trascendence
    restart: always

  postgres:
    restart: always
    image: postgres
    container_name: demo-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - trascendence
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: demo-pgadmin #you can change this
    depends_on:
      - postgres
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
      restart: always
    networks:
      - trascendence

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: "hpme/${USER}/data/postgres_data"
      o: bind

networks:
  trascendence:
    name: trascendence
    driver: bridge
