services:
  postrgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
    
  backend:
    depend_on:
      -postrgres
    container_name: backend
    build: django/backend/
    image: backend
    ports:
      - "8000:8000"
    restart: always  